DROP TABLE IF EXISTS CHUNKS;
DROP TABLE IF EXISTS FILES;
DROP TABLE IF EXISTS STATUS;

CREATE TABLE IF NOT EXISTS STATUS
(
    ID   INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS FILES
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    FILE_NAME   TEXT     NOT NULL,
    CONTENT     TEXT     NOT NULL,
    TAG         TEXT     NOT NULL,
    STATUS_ID   INTEGER  NOT NULL,
    MODEL_USED  TEXT     NULL,
    CREATED_AT  DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  DATETIME NULL,
    RETRY_COUNT INTEGER  DEFAULT 0,
    MIME_TYPE   TEXT     NOT NULL,
    EXT         TEXT     NOT NULL,
    FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CHUNKS
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    FILE_ID     INTEGER,
    CONTENT     TEXT     NOT NULL,
    TOKENS      INTEGER,
    STATUS      INTEGER  DEFAULT 0,
    RETRY_COUNT INTEGER  DEFAULT 0,
    CREATED_AT  DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  DATETIME NULL,
    FOREIGN KEY (FILE_ID) REFERENCES FILES (ID) ON DELETE CASCADE
);
DROP TABLE IF EXISTS vss_chunks;
CREATE VIRTUAL TABLE IF NOT EXISTS vss_chunks USING vec0
(
    chunk_id INTEGER PRIMARY KEY,
    file_id INTEGER,
    embedding float [384]
);
DROP VIEW IF EXISTS TAGS;

CREATE VIEW TAGS AS
SELECT DISTINCT F.TAG
FROM FILES F
ORDER BY 1;

DROP VIEW IF EXISTS DATALIST_AMM;
CREATE VIEW DATALIST_AMM AS
SELECT F.ID                      FILE_ID,
       C.ID                      CHUNK_ID,
       (CASE
            WHEN S.NAME = 'OK' AND C.STATUS = 1 THEN 'SUCCESS'
            WHEN S.NAME = 'KO' THEN 'EXCEPTION FILE'
            WHEN C.STATUS = 2 THEN 'EXCEPTION CHUNK'
            WHEN C.STATUS = 0 AND S.NAME = 'pending' THEN 'WAIT CHUNK'
            ELSE S.NAME
           END)                  STATUS,
       F.FILE_NAME,
       LENGTH(F.CONTENT)         LEN_TEXT_FILE,
       SUBSTR(F.CONTENT, 0, 100) PREVIEW_CONTENT_FILE,
       F.CONTENT                 ALL_FILE_DATA,
       C.CONTENT                 CHUNK_CONTENT,
       (CASE
            WHEN LENGTH(C.CONTENT) <= 30 THEN 'LITTLE'
            WHEN LENGTH(C.CONTENT) >= 4000 THEN 'BIG'
            ELSE 'OK'
           END
           )                     SUCCESS_CHUNK,
       SUBSTR(C.CONTENT, 0, 100) PREVIEW_CONTENT_CHUNCK,
       (CASE
            WHEN V.embedding IS NOT NULL THEN (
                CASE WHEN vec_length(V.embedding) = 384 THEN 'OK' ELSE 'KO' END
                )
            ELSE NULL END)       LEN_EMB,
       F.TAG,
       F.CREATED_AT,
       F.UPDATED_AT              UPDATE_FILES,
       C.UPDATED_AT              UPDATE_CHUNK
FROM FILES F
         JOIN STATUS S ON S.ID = F.STATUS_ID
         LEFT JOIN CHUNKS C ON C.FILE_ID = F.ID
         LEFT JOIN vss_chunks V ON V.CHUNK_ID = C.ID
ORDER BY F.CREATED_AT, F.UPDATED_AT, C.UPDATED_AT;

DROP VIEW IF EXISTS DATALIST;
CREATE VIEW DATALIST AS
SELECT TT.FILE_ID,
       TT.FILE_NAME,
       TT.PREVIEW_CONTENT_FILE,
       TT.TAG,
       TT.CREATED_AT,
       TT.UPDATED_AT,
       (CASE
            WHEN TT.STATUS_NAME = 'OK' AND TT.TOT_CHUNKS = TT.ELABORATE AND TT.TOT_CHUNKS = TT.TOT_EMB THEN 'SUCCESS'
            WHEN TT.STATUS_NAME = 'processing' AND TT.TOT_EMB = 0 THEN 'WAIT EMBED'
            WHEN TT.STATUS_NAME = 'KO' THEN 'EXCEPTION FILE'
            WHEN TT.EXCEPTION > 0 THEN 'EXCEPTION CHUNK'
            WHEN TT.NOT_ELABORATE > 0 AND TT.STATUS_NAME = 'processing' THEN 'WAIT CHUNK'
            ELSE TT.STATUS_NAME
           END) STATUS
FROM (SELECT F.ID                                                                  FILE_ID,
             S.NAME                                                                STATUS_NAME,
             (SELECT COUNT(*) FROM CHUNKS C WHERE C.FILE_ID = F.ID)                TOT_CHUNKS,
             (SELECT COUNT(*) FROM CHUNKS C WHERE C.FILE_ID = F.ID AND STATUS = 0) NOT_ELABORATE,
             (SELECT COUNT(*) FROM CHUNKS C WHERE C.FILE_ID = F.ID AND STATUS = 2) EXCEPTION,
             (SELECT COUNT(*) FROM CHUNKS C WHERE C.FILE_ID = F.ID AND STATUS = 2) ELABORATE,
             (SELECT COUNT(*) FROM vss_chunks V WHERE V.FILE_ID = F.ID)            TOT_EMB,
             F.FILE_NAME,
             SUBSTR(F.CONTENT, 0, 100)                                             PREVIEW_CONTENT_FILE,
             F.TAG,
             F.CREATED_AT,
             F.UPDATED_AT
      FROM FILES F
               JOIN STATUS S ON S.ID = F.STATUS_ID
      ORDER BY F.CREATED_AT, F.UPDATED_AT) TT;

SELECT
    C.CONTENT,
    vec_distance_cosine(v.embedding, ?) AS distance
    FROM vss_chunks V
JOIN CHUNKS C ON C.ID = V.CHUNK_ID
JOIN FILES F ON F.ID = C.FILE_ID
WHERE F.TAG = ?
ORDER BY distance LIMIT 3;