DROP TABLE IF EXISTS CHUNKS;
DROP TABLE IF EXISTS FILES;
DROP TABLE IF EXISTS STATUS;

CREATE TABLE IF NOT EXISTS STATUS
(
    ID   INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS FILES
(
    ID         INTEGER PRIMARY KEY AUTOINCREMENT,
    FILE_NAME  TEXT    NOT NULL,
    CONTENT    TEXT    NOT NULL,
    TAG        TEXT    NOT NULL,
    STATUS_ID  INTEGER NOT NULL,
    MODEL_USED TEXT NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NULL,
    RETRY_COUNT INTEGER DEFAULT  0,
    MIME_TYPE TEXT NOT NULL,
    EXT TEXT NOT NULL,
    FOREIGN KEY (STATUS_ID) REFERENCES STATUS(ID) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS CHUNKS
(
    ID         INTEGER PRIMARY KEY AUTOINCREMENT,
    FILE_ID    INTEGER,
    CONTENT    TEXT NOT NULL,
    TOKENS INTEGER,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NULL,
    FOREIGN KEY (FILE_ID) REFERENCES FILES(ID) ON DELETE CASCADE
    );

CREATE VIRTUAL TABLE IF NOT EXISTS vec_chunks USING vec0(
    chunk_id INTEGER PRIMARY KEY,
    file_id INTEGER,
    embedding float[768]
);